version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "chore"
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - "dev-sec-ops"
