# Pre-commit hook configuration for the MoJ scanner:
# - Runs the devsecops-hooks Docker image to scan for hardcoded secrets/credentials
# - Runs on every invocation, and does not pass filenames
# - Excludes hidden files/directories from scanning

- id: baseline
  name: "🔐 Ministry of Justice - Scanner"
  description: "MoJ's pre commit hooks scans for hardcoded secrets and credentials using CLI commands of choice."
  entry: "ghcr.io/ministryofjustice/devsecops-hooks:v1.4.0"
  language: "docker_image"
  fail_fast: false
  always_run: true
  verbose: true
  pass_filenames: false
  exclude: "^\\..*|/\\..*"
