# Executes all pre-commit hooks on pull requests
# Includes security scanning, linting, spellcheck, and config validation
# Trigger: pull_request (all branches) | Permissions: contents:read, issues:read, pull-requests:read

name: Git hooks 🪝
run-name: Git hooks 🪝

on:
  pull_request:
    branches: ["**"]

permissions: {}

env:
  environment: base
  timezone: ${{ vars.TIMEZONE }}

jobs:
  # 1. Setup infrastructure
  setup:
    name: Infrastructure 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
      timezone: ${{ env.timezone }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.environment }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.timezone }}"

  # 2. Execute pre-commit hooks
  hooks:
    permissions:
      contents: read
      issues: read
      pull-requests: read

    name: Hooks 🪝
    needs: setup
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: ./.python-version

      - name: Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: SLSA
        uses: ministryofjustice/devsecops-actions/sca/slsa@e3c63a5986ea6e7d57d38b7f72e5b8cf08dc7020 # v1.4.0

      - name: Install
        working-directory: ./
        run: |
          python -m pip install -r requirements.txt
          npm ci --ignore-scripts

      - name: Execute
        run: pre-commit run --all-files
