name: Release
run-name: Release

on:
  push:
    branches: [main]

permissions: {}

env:
  environment: base

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    name: Release
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.environment }}

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Release
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  attest:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}

    permissions:
      contents: read
      id-token: write
      attestations: write

    name: Attest
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: scripts/gitleaks.sh
